---
- hosts: test
  vars:
    http_port: 80
    max_clients: 200
  remote_user: root
  tasks:
    - name: abc
      action: apt name=apache2 state=latest
    - name: xyz
      action: service name=apache2 state=started enabled=yes
